# Generated by Django 4.0 on 2022-01-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='document_upload/')),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.registration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.registration')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
